[[tooling-maven]]
=== Maven

The following sections illustrate how <<tooling-maven-enhancement,bytecode enhancement>>,
<<tooling-maven-modelgen,metamodel generation>>, <<tooling-maven-reveng,reverse engineering>>,
<<tooling-maven-schema,schema management>>, and <<tooling-maven-transformhbm,HBM XML transformation>>
capabilities can be integrated into Maven builds.

[[tooling-maven-enhancement]]
==== Bytecode Enhancement

Hibernate provides a https://maven.apache.org/[Maven] plugin capable of providing
build-time enhancement of the domain model as they are compiled as part of a Maven
build.  See the section on <<BytecodeEnhancement>> for details
on the configuration settings.

[[maven-enhance-goal]]
===== *Enhance Goal* =====

An example of using the `enhance` goal of the plugin is shown below. By default the plugin will
perform bytecode enhancement for lazy initialization and dirty tracking. See <<maven-enhance-configuration, below>>
for more details on the available parameters.

.Apply the Bytecode Enhancement plugin
====
[source,xml,subs="attributes+"]
----
include::extras/maven-example.pom[]
----
====

[[maven-enhance-configuration]]
===== *Enhance Configuration* =====

[[maven-enhance-classesDirectory-parameter]]
====== `*classesDirectory*` ======
This parameter points to the folder in which to look for classes to enhance.
It defaults to the value of `{project.build.directory}/classes` and thus in most cases to `target/classes`.
If both `classesDirectory` and <<maven-enhance-filesets-parameter,fileSets>> are set,
`fileSets` takes precedence.

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <classesDirectory>path-to-some-folder</classesDirectory>
  </configuration>
  [...]
</execution>
[...]
----
====

[[maven-enhance-filesets-parameter]]
====== `*fileSets*` ======
This optional parameter comes in handy when you need to filter the classes that you want to enhance.
More information on how to use filesets is to be found on the
https://maven.apache.org/shared/file-management/fileset.html[fileset documentation page].
If both <<maven-enhance-classesDirectory-parameter, classesDirectory>> and `fileSets` are set,
`fileSets` takes precedence.

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <fileSets>
      <fileset dir="path-to-some-folder">
        <exclude name='Baz.class' />
      </fileset>
    </fileSets>
  </configuration>
  [...]
</execution>
[...]
----
====

[[maven-enhance-enableLazyInitialization-parameter]]
===== `*enableLazyInitialization*` =====
This parameter has a default value of `true`. It indicates whether the enhance goal should perform the changes
to enable <<BytecodeEnhancement-lazy-loading,lazy loading>>.
The parameter has been deprecated for removal. After this removal, <<BytecodeEnhancement-lazy-loading,lazy loading>>
will always be enabled.

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <enableLazyInitialization>false</enableLazyInitialization>
  </configuration>
  [...]
</execution>
[...]
----
====

[[maven-enhance-enableDirtyTracking-parameter]]
===== `*enableDirtyTracking*` =====
This parameter has a default value of `true`. It indicates whether the enhance task should perform the changes
to enable <<BytecodeEnhancement-dirty-tracking,dirty tracking>>.
The parameter has been deprecated for removal. After this removal, <<BytecodeEnhancement-dirty-tracking,dirty tracking>>
will always be enabled.

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <enableDirtyTracking>false</enableDirtyTracking>
  </configuration>
  [...]
</execution>
[...]
----
====

[[maven-enhance-enableAssociationManagement-parameter]]
===== `*enableAssociationManagement*` =====
This parameter has a default value of `false`. It indicates whether the enhance task should perform the changes
to enable <<BytecodeEnhancement-dirty-tracking-bidirectional,association management>>.

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <enableAssociationManagement>true</enableAssociationManagement>
  </configuration>
  [...]
</execution>
[...]
----
====

[[maven-enhance-enableExtendedEnhancement-paremeter]]
===== `*enableExtendedEnhancement*` =====
This parameter has a default value of `false`. It indicates whether the enhance task should perform the changes
to enable the extended enhancement: enhancement of non-entities to trigger lazy-loading and inline dirty tracking
even when accessing entity fields directly..

====
[source,xml]
----
[...]
<execution>
  <configuration>
    <enableExtendedEnhancement>true</enableExtendedEnhancement>
  </configuration>
  [...]
</execution>
[...]
----
====


[[tooling-maven-modelgen]]
==== Annotation processor for static metamodel and repositories

<<tooling-modelgen,Static metamodel and repository>> generation should be integrated into a maven project through the annotation processor
paths of the maven compiler plugin.

.Integrate the metamodel generator
====
[source,xml,subs="attributes+"]
----
include::extras/maven-example-metamodel.pom[]
----
====


[[tooling-maven-reveng]]
==== Reverse Engineering

Hibernate provides a Maven plugin for <<tooling-reveng,reverse engineering>> an existing database
into Java entities, mapping files, DAOs, DDL scripts, and Flyway migrations.


[[tooling-maven-reveng-plugin]]
===== Plugin Declaration

Add the `hibernate-maven-plugin` to your POM:

[source,xml,subs="attributes+"]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-maven-plugin</artifactId>
            <version>{fullVersion}</version>
            <executions>
                <execution>
                    <id>generate-entities</id>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>hbm2java</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----


[[tooling-maven-reveng-goals]]
===== Available Goals

The plugin provides the following goals:

`hbm2java`:: Generates Java entity classes from the database schema. Binds to the `generate-sources` phase by default.
`hbm2ddl`:: Generates DDL scripts from the database schema. Binds to the `generate-resources` phase by default.
`hbm2dao`:: Generates Data Access Object (DAO) classes. Binds to the `generate-sources` phase by default.
`generateHbm`:: Generates `hbm.xml` mapping files from the database schema. Binds to the `generate-sources` phase by default.


[[tooling-maven-reveng-common-params]]
===== Common Configuration Parameters

The following parameters are shared by the `hbm2java`, `hbm2ddl`, `flyway`, `hbm2dao`, and `generateHbm` goals:

`propertyFile`:: Path to a properties file containing JDBC connection settings. Default: `${project.basedir}/src/main/resources/hibernate.properties`.
`packageName`:: The default Java package name for generated classes.
`revengFile`:: Path to a reverse engineering configuration XML file for customizing schema selection, type mappings, and filters.
`revengStrategy`:: Fully qualified class name of a custom reverse engineering strategy. Extend `DefaultReverseEngineeringStrategy` and override methods to customize class names, type mappings, etc.
`detectManyToMany`:: If `true`, pure many-to-many link tables (tables whose primary key consists of exactly two foreign keys and no other columns) are mapped as many-to-many associations. Default: `true`.
`detectOneToOne`:: If `true`, a one-to-one association is created for each foreign key found. Default: `true`.
`detectOptimisticLock`:: If `true`, columns named `VERSION` or `TIMESTAMP` with appropriate types are mapped as `@Version` properties. Default: `true`.
`createCollectionForForeignKey`:: If `true`, a collection mapping is generated for each foreign key. Default: `true`.
`createManyToOneForForeignKey`:: If `true`, a many-to-one association is created for each foreign key found. Default: `true`.


[[tooling-maven-reveng-hbm2java-params]]
===== hbm2java Parameters

`outputDirectory`:: The directory into which entity classes are generated. Default: `${project.build.directory}/generated-sources/`.
`ejb3`:: Whether to generate Jakarta Persistence annotations. Default: `true`.
`jdk5`:: Whether to use JDK 5+ constructs such as generics and static imports. Default: `true`.
`templatePath`:: Path to a directory containing custom FreeMarker templates.


[[tooling-maven-reveng-hbm2ddl-params]]
===== hbm2ddl Parameters

`outputDirectory`:: The directory into which DDL scripts are generated. Default: `${project.build.directory}/generated-resources/`.
`outputFileName`:: The filename of the generated DDL script. Default: `schema.ddl`.
`targetTypes`:: The type of output to produce: `DATABASE` (export to the database), `SCRIPT` (write to a script file), or `STDOUT` (write to standard output). Default: `SCRIPT`.
`schemaExportAction`:: The DDL statements to create: `NONE`, `CREATE`, `DROP`, or `BOTH` (drop then create). Default: `CREATE`.
`delimiter`:: The end-of-statement delimiter. Default: `;`.
`format`:: Whether to format the SQL output. Default: `true`.
`haltOnError`:: Whether to stop on the first error. Default: `true`.


[[tooling-maven-reveng-hbm2dao-params]]
===== hbm2dao Parameters

`outputDirectory`:: The directory into which DAO classes are generated. Default: `${project.build.directory}/generated-sources/`.
`ejb3`:: Whether to use Jakarta Persistence features. Default: `false`.
`jdk5`:: Whether to use JDK 5+ constructs. Default: `false`.
`templatePath`:: Path to a directory containing custom FreeMarker templates.


[[tooling-maven-reveng-example]]
===== Example

The following POM generates JPA entity classes from an H2 database:

[source,xml,subs="attributes+"]
----
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.2.224</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-maven-plugin</artifactId>
                <version>{fullVersion}</version>
                <executions>
                    <execution>
                        <id>generate-entities</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>hbm2java</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

By default, the plugin reads JDBC connection settings from `src/main/resources/hibernate.properties`.
Run the generation with:

[source,bash]
----
mvn generate-sources
----


[[tooling-maven-schema]]
==== Schema Management

The `hibernate-maven-plugin` provides a `flyway` goal that generates Flyway versioned migration
files by comparing JPA entity classes against the existing database using `SchemaUpdate`. Unlike
the reverse engineering goals which read _from_ the database, the Flyway goal works in the
opposite direction: entity classes define the target schema, and the migration captures the diff.

Entity classes are discovered via JPA bootstrapping from a `persistence.xml`.


[[tooling-maven-schema-flyway]]
===== flyway Goal

The `flyway` goal binds to the `process-classes` phase by default, since it needs compiled entity classes on the classpath.

`persistenceUnit`:: The name of the JPA persistence unit to use for entity discovery. The `META-INF/persistence.xml` must be on the classpath. Default: `default`.
`outputDirectory`:: The directory into which the migration file is generated. Default: `${project.build.directory}/generated-resources/`.
`migrationVersion`:: The version number for the Flyway migration file. This becomes the `V{version}` prefix in the filename. Default: `1`.
`migrationDescription`:: A human-readable description for the migration. Spaces are replaced with underscores. This becomes the `__{description}` suffix in the filename. Default: `hibernate_schema_update`.
`delimiter`:: The end-of-statement delimiter. Default: `;`.
`format`:: Whether to format the SQL output. Default: `true`.
`haltOnError`:: Whether to stop on the first error. Default: `true`.

The generated file follows the Flyway naming convention: `V{version}__{description}.sql`.
For example, with the default settings, the generated file is named `V1__hibernate_schema_update.sql`.

The migration contains ALTER and CREATE statements representing the difference between
the current Hibernate entity model and the existing database schema, generated by `SchemaUpdate`.
This is useful when entity classes have been modified and you need to generate a migration
script that brings the database in sync with the updated model.


[[tooling-maven-schema-example]]
===== Example

Create a `META-INF/persistence.xml` in `src/main/resources/` with your JDBC connection settings:

[source,xml]
----
<persistence xmlns="https://jakarta.ee/xml/ns/persistence" version="3.0">
    <persistence-unit name="default">
        <properties>
            <property name="jakarta.persistence.jdbc.driver" value="org.h2.Driver"/>
            <property name="jakarta.persistence.jdbc.url" value="jdbc:h2:tcp://localhost/./mydb"/>
            <property name="jakarta.persistence.jdbc.user" value="sa"/>
            <property name="jakarta.persistence.jdbc.password" value=""/>
        </properties>
    </persistence-unit>
</persistence>
----

Hibernate scans the persistence unit root (the classpath entry containing `META-INF/persistence.xml`)
for annotated entity classes automatically. In Maven, resources and compiled classes share the same
`target/classes/` directory, so scanning finds entities without further configuration.
If you prefer to list entity classes explicitly, add `<class>` elements and
`<exclude-unlisted-classes>true</exclude-unlisted-classes>` to the persistence unit.

Configure the plugin in your POM:

[source,xml,subs="attributes+"]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-maven-plugin</artifactId>
            <version>{fullVersion}</version>
            <executions>
                <execution>
                    <id>flyway-migration</id>
                    <goals>
                        <goal>flyway</goal>
                    </goals>
                    <configuration>
                        <persistenceUnit>default</persistenceUnit>
                        <migrationVersion>2</migrationVersion>
                        <migrationDescription>add email column</migrationDescription>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

Run the generation with:

[source,bash]
----
mvn process-classes
----

This compiles the entity classes and then generates `V2__add_email_column.sql` in the output directory.


[[tooling-maven-transformhbm]]
==== HBM XML Transformation

The `hibernate-maven-plugin` provides a `transformHbm` goal that transforms legacy `hbm.xml` mapping files
into ORM `mapping.xml` files. This goal does not connect to a database -- it converts existing HBM mappings.


[[tooling-maven-transformhbm-params]]
===== transformHbm Parameters

`inputFolder`:: The folder containing `hbm.xml` files to transform. Files are discovered recursively. Default: `${project.basedir}/src/main/resources`.
`format`:: Whether to format the output XML. Default: `true`.
