CREATE TABLE PERSON (ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID))
CREATE TABLE ITEM (ID INT NOT NULL, NAME VARCHAR(20), OWNER_ID INT NOT NULL, PRIMARY KEY (ID), FOREIGN KEY (OWNER_ID) REFERENCES PERSON(ID))
